### ISSUE TITLE
Will you hare a pretrained model?

### ISSUE THREAD

**Issue by MariasStory** [hit-thusz-RookieCJ/fullsubnet-plus.github.io#1]
Hi @hit-thusz-RookieCJ, the new model FullSubNet+ looks very promising.
Can you please share a pretrained model?

**Comment by RookieJunChen** [comment]
Sorry, our pre-trained model will be released after this paper is accepted.

**Comment by RookieJunChen** [comment]
The source code and pre-trained models are publicly available, you can refer to https://github.com/hit-thusz-RookieCJ/FullSubNet-plus.

**Comment by RookieJunChen** [comment]
This paper will be published later.
